import Head from "next/head";
import Banner from "../components/Banner/Banner";
import SectionCard from "../components/Card/SectionCard";
import Navbar from "../components/Nav/Navbar";

import {
	getPopularVideos,
	getVideos,
	getWatchItAgainVideos,
} from "../lib/videos";
import styles from "../styles/Home.module.css";
import RedirectUser from "../utils/RedirectUser";

export async function getServerSideProps(context) {
	const { userId, token } = await RedirectUser(context);

	if (!userId) {
		return {
			props: {},
			redirect: {
				destination: "/login",
				permanent: false,
			},
		};
	}

	const disneyVideos = await getVideos("disney trailer");
	const productivityVideos = await getVideos("productivity");
	const travelVideos = await getVideos("travel");
	const popularVideos = await getPopularVideos("popular");

	const watchItAgainVideos = await getWatchItAgainVideos(userId, token);

	return {
		props: {
			disneyVideos,
			productivityVideos,
			popularVideos,
			travelVideos,
			watchItAgainVideos,
		},
	};
}

export default function Home({
	disneyVideos,
	productivityVideos,
	popularVideos,
	travelVideos,
	watchItAgainVideos = [],
}) {
	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className={styles.main}>
				<Navbar username="mykobacal23@gmail.com" />
				<Banner
					videoId="4444"
					title="Clifford the red dog"
					subTitle="a very cute dog"
					imgUrl="/static/clifford.jpg"
				/>
				<div className={styles.sectionWrapper}>
					<SectionCard
						title="Disney"
						videos={disneyVideos}
						size="large"
					/>
					{watchItAgainVideos?.length !== 0 ? (
						<SectionCard
							title="Watch it Again"
							videos={watchItAgainVideos}
							size="small"
						/>
					) : null}
					<SectionCard
						title="Travel"
						videos={travelVideos}
						size="small"
					/>
					<SectionCard
						title="Productivity"
						videos={productivityVideos}
						size="medium"
					/>
					<SectionCard
						title="Popular"
						videos={popularVideos}
						size="small"
					/>
				</div>
			</div>
		</div>
	);
}
